version: "3.8"

services:
  passgen:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - ./:/go/src/app
    networks:
    - passgen-network

networks:
  passgen-network:
    driver: bridge